# Use the official WordPress image as a base
FROM wordpress:latest

# Set the working directory
WORKDIR /var/www/html

# Install git
RUN apt-get update && apt-get install -y git

# Remove the existing content in the html directory
RUN rm -rf /var/www/html/*

# Remove the temporary directory if it exists and clone the repository
RUN rm -rf /tmp/propell && git clone https://github.com/dinhhuy2603/propell.git /tmp/propell

# Copy the files from the temporary directory to the working directory
RUN cp -r /tmp/propell/* /var/www/html/
# Ensure the right permissions
RUN chown -R www-data:www-data /var/www/html
