version: '3.8'

services:
  wordpress:
    build: .
    image: wordpress:latest
    container_name: wordpress
    platform: linux/amd64
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: propell-dev
      WORDPRESS_DB_PASSWORD: propell-dev
      WORDPRESS_DB_NAME: propell-dev
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: wordpress_db
    ports:
      - "3306:3306" # Expose MySQL port
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: propell-root
      MYSQL_DATABASE: propell-dev
      MYSQL_USER: propell-dev
      MYSQL_PASSWORD: propell-dev
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:

